FROM envoyproxy/envoy:v1.18.6

COPY ./envoy.yaml /etc/envoy.yaml
COPY main.wasm ./examples/dispatch_call_on_tick/main.wasm
RUN chmod go+r /etc/envoy.yaml
CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "--service-cluster", "dispatch"]
